---
# Validates vault listings with params.

authors:
  - Intesar Shannan Mohammed

endpoint: /system-settings?page=0&pageSize=101

method: GET

assertions:
  - "@StatusCode == 200"
  - "@Response.errors == true"

tags:
  - V1
