---

authors:
  - Intesar Shannan Mohammed

endpoint: /system-settings/1
method: PUT
auth: NONE
severity: Critical
category: Security_UnSecured
# Auth required for this endpoint.

testCases:
  - id: 1
    body:
      '{}'

assertions:
  - "@StatusCode == 401"

tags:
  - V2

policies:
  logger: DEBUG
