---

authors:
  - Intesar Shannan Mohammed

endpoint: /system-settings/1
method: GET
auth: NONE
severity: Critical
category: Security_UnSecured
# Auth required for this endpoint.

assertions:
  - "@StatusCode == 401"

tags:
  - V2

policies:
  logger: DEBUG
